package tests

var Port = 7540
var DBFile = "../scheduler.db"
var FullNextDate = true
var Search = true
var Token = `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MzI4MjE5OTUsInBhc3N3b3JkSGFzaCI6IjM2MzkzNjMxMzI2NjYyMzczNTM1NjQzNjM2NjIzNDYxMzIzNzM1MzgzOTM2MzkzODMxMzgzNzM0NjMzNDM2MzIzMTMwNjYzNDYxNjY2MjYxNjMzNzM2MzczMzYyNjM2MjMwNjM2NTM0MzA2NDMzNjMzNjYxMzAzMTM2MzA2NDM1In0.Pc9tebN_l5MclX6mHzeIDM5p8hYF6GAny0FHfRBxg_A`
